gemini:
  # Required: API Keys
  api_keys:
    - "your-api-key-1"
    - "your-api-key-2"

  # Optional: Generation Settings
  generation:
    temperature: 0.7
    top_p: 1.0
    top_k: 40
    max_output_tokens: 8192
    stop_sequences: []
    response_mime_type: "text/plain"

  # Optional: Rate Limiting
  rate_limits:
    requests_per_minute: 60
    reset_window: 60  # seconds

  # Optional: Strategies
  strategies:
    content: "round_robin"  # round_robin, fallback, retry
    key_rotation: "smart_cooldown"  # smart_cooldown, sequential, round_robin, least_used

  # Optional: Retry Settings
  retry:
    max_attempts: 3
    delay: 30  # seconds

  # Optional: Model Settings
  default_model: "gemini-2.0-flash-exp"
  system_instruction: null  # Custom system prompt
