gemini:
  # Required: API Keys
  api_keys:
    - "AIzaSyBmWf7COPcA6r62lDUoZ3x0dp47iy7ttSk" #lethanhson99907
    - "AIzaSyAIsEdv54bT-UixRDnG5aoOGXbGaybPHMM" #lethanhson99908
    
  # Optional: Generation Settings
  generation:
    temperature: 0.7
    top_p: 1.0
    top_k: 40
    max_output_tokens: 8192
    stop_sequences: []
    response_mime_type: "text/plain"

  # Optional: Rate Limiting
  rate_limits:
    requests_per_minute: 60
    reset_window: 60  # seconds

  # Optional: Strategies
  strategies:
    content: "round_robin"  # round_robin, fallback, retry
    key_rotation: "smart_cooldown"  # smart_cooldown, sequential, round_robin, least_used

  # Optional: Retry Settings
  retry:
    max_attempts: 3
    delay: 30  # seconds

  # Optional: Model Settings
  default_model: "gemini-2.0-flash"
  system_instruction: null  # Custom system prompt

  # Embedding Settings
  embedding:
    default_model: "gemini-embedding-exp-03-07"  # Model mặc định cho embedding
    dimensions: 768  # Số chiều mặc định (tùy thuộc vào model)
    batch_size: 10  # Số lượng văn bản tối đa trong một lần gọi API
    task_types:
      default: "SEMANTIC_SIMILARITY"  # Task type mặc định
      supported:
        - "SEMANTIC_SIMILARITY"
        - "CLASSIFICATION" 
        - "CLUSTERING"
        - "RETRIEVAL_DOCUMENT"
        - "RETRIEVAL_QUERY"
        - "QUESTION_ANSWERING"
        - "FACT_VERIFICATION"
        - "CODE_RETRIEVAL_QUERY"

# --- Proxy Configuration ---
proxy:
  # Required: Choose the proxy mode.
  # Options:
  #   'swiftshadow': Use the SwiftShadow library to get dynamic proxies.
  #                  Requires SwiftShadow to be installed and working.
  #   'custom':      Use the static list of proxies defined below in 'custom_list'.
  # Default: If the 'proxy' section or the 'mode' key is missing, it defaults to 'swiftshadow'.
  mode: custom  # <--- CHANGE THIS: 'custom' or 'swiftshadow'

  # Required ONLY if mode is 'custom':
  # A list of your custom proxy server URLs.
  # The script will randomly select one proxy from this list for each request.
  # Format: scheme://[user:password@]host:port
  custom_list:
    - "http://brd-customer-hl_8d87b67a-zone-residential_proxy1:eb0e1vrv5v2g@brd.superproxy.io:33335" # Example from your request
    - "https://brd-customer-hl_8d87b67a-zone-residential_proxy1:eb0e1vrv5v2g@brd.superproxy.io:33335"
    # - "https://user2:pass2@another-proxy.com:8080" # Example with HTTPS
    # - "http://some-other-proxy.org:9999"          # Example without authentication
    # - "socks5://user3:pass3@socks-proxy.net:1080" # SOCKS proxy (ensure tls_requests supports socks format if needed, typically http/https are used for its 'proxies' dict)
